version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bike
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - postgres
    restart: unless-stopped

volumes:
  postgresdata:
    driver: local

networks:
  postgres:
    driver: bridge
