version: '3.8'
services:
  spring-boot-es1:
    image: actlem/spring-boot-es
    container_name: spring-boot-es1
    environment:
      ES_HOST: 'es01:9200'
    networks:
      - elastic
    depends_on:
      - es01
      - es02
      - es03
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8080/admin/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

  spring-boot-es2:
    image: actlem/spring-boot-es
    container_name: spring-boot-es2
    environment:
      ES_HOST: 'es01:9200'
    networks:
      - elastic
    depends_on:
      - es01
      - es02
      - es03
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8080/admin/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

  load-balancer:
    image: nginx:1.17.10-alpine
    container_name: load-balancer
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - elastic
    depends_on:
      - spring-boot-es1
      - spring-boot-es2
  
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    networks:
      - elastic
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata03:/usr/share/elasticsearch/data
    networks:
      - elastic
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local

networks:
  elastic:
    driver: bridge
