# This workflow will build the Spring Boot with Generator application with Gradle

name: Build Bike Generator

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - 'backend/java/commons/**'
      - 'backend/java/commons-test/**'
      - 'backend/java/bike-generator/**'

jobs:
  build-bike-generator:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Grant execute permission for gradlew
        run: chmod +x backend/java/gradlew
      - name: Build with Gradle
        run: cd backend/java && ./gradlew :bike-generator:build
