# This workflow will build the Spring Boot with Elasticsearch application with Gradle

name: Build Spring Boot with Elasticsearch

on:
  push:
    paths:
      - 'spring-boot-elasticsearch/**'
  pull_request:
    paths:
      - 'spring-boot-elasticsearch/**'

jobs:
  build-spring-boot-es:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Grant execute permission for gradlew
        run: chmod +x spring-boot-elasticsearch/gradlew
      - name: Build with Gradle
        run: ./spring-boot-elasticsearch/gradlew build
